### ISSUE TITLE
Switch runTSNE to runUMAP

### ISSUE THREAD

**Issue by kevinrue** [iSEE/iSEEWorkshop2020#11]
Note that this will require the package `uwot` instead of `Rtsne`

**Comment by csoneson** [comment]
`runUMAP` is added in 8b22f7e. Not sure if the UMAP is easier to interpret though, so I didn't swap the visualizations in the examples.

**Comment by federicomarini** [comment]
According to the extra dependency cost (& computing time?), maybe we can just keep all three redDims in the sce object.
Could help in showcasing that "we cover all cases" - even if for real it is not really *on us*...

**Comment by csoneson** [comment]
Yes, I agree, it doesn't really make a big difference in computation time.

**Comment by kevinrue** [comment]
I don't mind a bit more compute time. I haven't seen the UMAP yet, but it's a fairly popular demand these days, so it wouldn't hurt to have it around.

I see this.
![image](https://user-images.githubusercontent.com/5769108/85231578-39b66880-b3f0-11ea-9085-870977263734.png)
![image](https://user-images.githubusercontent.com/5769108/85231579-3f13b300-b3f0-11ea-92cc-26dd29a53652.png)

In this case the UMAP's "compactness" does not help visualisation, but it kinda helps selecting the major clusters more easily, given that it pushed them further apart.

With that said, I think we can close the issue with the current setup, i.e.:

- compute UMAP
- don't use it in the screenshot (easier to read)
- feel free to do a little detour through the UMAP view during live demos, to illustrate the point

**Comment by csoneson** [comment]
Sounds good to me
