### ISSUE TITLE
Avoid potential confusion due to sce1

### ISSUE THREAD

**Issue by kevinrue** [iSEE/iSEEWorkshop2020#18]
In section 'Saving and restoring the state of the application'
We could just use `sce` instead of `sce1` in the following chunk
```
iSEE(sce1, initial = initial)
```

**Comment by csoneson** [comment]
I'm not sure if this would be less confusing - the table would not look the same as in the previous application (`sce` has more columns in the colData).

**Comment by kevinrue** [comment]
Oh I see.
Indeed, this section 'Saving and restoring the state of the application' directly follows the app that was using `sce1`, so using `sce1` again flows more naturally. 
Closing this.
