### ISSUE TITLE
unused object

### ISSUE THREAD

**Issue by kevinrue** [iSEE/iSEEWorkshop2020#32]
https://github.com/iSEE/iSEEWorkshop2020/blob/3042c14e1ae36bff714732dd6190a5ea94d0bb3b/vignettes/iSEE-lab.Rmd#L1132

`custom_panel` is not used anywhere, remove?

**Comment by federicomarini** [comment]
Looks safe for me to remove

**Comment by kevinrue** [comment]
thanks for reminding me - i keep forgetting

**Comment by federicomarini** [comment]
thank my detailed approach with sifting tons of emails 😄

**Comment by kevinrue** [comment]
Fixed by 8025e1d58ed23c5f60c6af670acf89a024fcc12b
